// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9FJ4PRjxtlcH9l9VVAn4vD0SuogdXnKU',
    appId: '1:996825782685:web:6fd5e8faa778a061943774',
    messagingSenderId: '996825782685',
    projectId: 'harmony-music-eb7ee',
    authDomain: 'harmony-music-eb7ee.firebaseapp.com',
    storageBucket: 'harmony-music-eb7ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfASrgHmZzGG-6VrxZLNJkNO0rtvRX2FE',
    appId: '1:996825782685:android:fb8cd61f6882db01943774',
    messagingSenderId: '996825782685',
    projectId: 'harmony-music-eb7ee',
    storageBucket: 'harmony-music-eb7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDowCS-Vle9Wo-dtHWC0B1Z7OZaOR_OOys',
    appId: '1:996825782685:ios:f7d56bb020e5ea7a943774',
    messagingSenderId: '996825782685',
    projectId: 'harmony-music-eb7ee',
    storageBucket: 'harmony-music-eb7ee.appspot.com',
    iosClientId: '996825782685-6pmj0uimv1298ngbpq32gkfnq2m1il3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDowCS-Vle9Wo-dtHWC0B1Z7OZaOR_OOys',
    appId: '1:996825782685:ios:4cdd818f692c64d2943774',
    messagingSenderId: '996825782685',
    projectId: 'harmony-music-eb7ee',
    storageBucket: 'harmony-music-eb7ee.appspot.com',
    iosClientId: '996825782685-39omgcuhclbrlohs8g0outsgajkcsd3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.harmony.RunnerTests',
  );
}
